# Variables
NAME        = backend-NODE
DOCKERFILE  = docker-compose.yaml

# DB connect
DB_HOST     = 127.0.0.1
DB_PORT     = 5432
DB_NAME     = postgres
DB_USERNAME = postgres
DB_PASSWORD = postgres

all:  local-up local-down local-ps db-init db-connect

.PHONY: local-ps
    local-ps:
    docker-compose -f $(DOCKERFILE) ps

# Run app locally
.PHONY: local-up
local-up:
    docker-compose -f $(DOCKERFILE) up -d
    @echo Local upping ... [OK]

# Stop local app
.PHONY: local-down
local-down:
    docker-compose -f $(DOCKERFILE) down
    @echo Local downing ... [OK]

# Initialize db
.PHONY: db-init
db-init:
    @echo "-- [DB INIT] --"
    docker exec -e PGHOST=$(DB_HOST) \
                 -e PGPORT=$(DB_PORT) \
                 -e PGDATABASE=$(DB_NAME) \
                 -e PGUSER=$(DB_USERNAME) \
                 -e PGPASSWORD=$(DB_PASSWORD) \
                 -it $(NAME)-db psql -c "CREATE ROLE backend SUPERUSER CREATEDB CREATEROLE BYPASSRLS REPLICATION;" "postgres://postgres:postgres@localhost:5432/postgres"

# Connect to db
.PHONY: db-connect
db-connect: 
    @echo "-- [DB CONNECT] --"
    docker exec -e PGHOST=$(DB_HOST)  -e PGPORT=$(DB_PORT)  -e PGDATABASE=$(DB_NAME)  -e PGUSER=$(DB_USERNAME)  -e PGPASSWORD=$(DB_PASSWORD)  -it $(NAME)-db psql
.PHONY: all local-up local-down local-ps db-init db-connect